version: '3.8'
services: 
    jenkins:
        container_name: jenkins
        image: local/jenkins
        build:
            context: .
            dockerfile: jenkins/Dockerfile
        ports: 
            - "8080:8080"
        volumes:
            - "/var/jenkins_home:/var/jenkins_home"
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks: 
            - net
    remote_host:
        container_name: remote_host
        image: local/remote_host
        build:
            context: .
            dockerfile: centos7/Dockerfile
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - net
    gitlab:
        container_name: gitlab
        image: gitlab/gitlab-ce:latest
        hostname: gitlab.example.com
        ports:
            - "8090:80"
        volumes:
            - "/srv/gitlab/config:/etc/gitlab"
            - "/srv/gitlab/logs:/var/log/gitlab"
            - "/srv/gitlab/data:/var/opt/gitlab"
        networks: 
            - net   
networks: 
    net:
        
